version: '3.7'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "127.0.0.1:6333:6333"  # REST API port, only accessible locally
      - "127.0.0.1:6334:6334"  # GRPC port, only accessible locally
    volumes:
      - ~/Library/Mobile Documents/com~apple~CloudDocs/wandering-rag-data/qdrant-storage:/qdrant/storage  # Store in iCloud
    environment:
      - QDRANT_ALLOW_RECOVERY=true  # Enable storage recovery if needed
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3 